spring:
  application:
    name: servicio-formacion
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: instancia_formacion
server:
  port: 8090
